### ISSUE TITLE
Ganglia RPMs from Sourceforge

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#18]
Don't get them from sourceforge!

**Comment by berghaus** [comment]
What other repository provides a version that supports override_hostname, i.e. >3.2?

**Comment by rptaylor** [comment]
Perhaps somewhere on https://github.com/ganglia ?
I'm sure you know Sourceforge hasn't been a very good place since it was purchased:
http://www.techrepublic.com/article/its-time-to-go-away-sourceforge/

**Comment by rptaylor** [comment]
The current cernvm-3.5.1 has
ganglia-gmond-3.7.1-2.el6.x86_64
and does not have libganglia installed. Seems that is not needed (unless compiling an application using the ganglia API I suppose). So our yaml doesn't need to install those RPMs manually anymore.
