### ISSUE TITLE
Install python-kerberos

### ISSUE THREAD

**Issue by berghaus** [hep-gc/cloudinit-userdata#19]
RUCIO requires python-kerberos cauing jobs to fail. We either need to be able to rely on CernVM to make python-kerberos available or install it ourselves.

**Comment by rptaylor** [comment]
It looks like further testing by Rod and Vincent suggest this is not the problem. python-kerberos is available in CVMFS and the PYTHONPATH apparently points to it. If you didn't have PYTHONPATH set up the same way in your interactive test, installing the RPM would provide the required libraries from an alternative source.
Rod was recently unable to reproduce the problem. 
I guess we should see how further investigation develops...

**Comment by rptaylor** [comment]
It seems the issue was due to file corruption by some unknown cause ... hopefully that doesn't happen again.
