### ISSUE TITLE
check authorized_keys file

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#27]

**Comment by rptaylor** [comment]
Happens on ATLAS tenant, cc-east and cc-west. Possibly others.

**Comment by mhpx** [comment]
well I was just able to log in to a recent machine since you updated the yaml to include my key.  authorized_keys has all the correct stuff.  So maybe whatever the problem was was resolved when you updated the yaml, or was a temporary issue with the metadata server

**Comment by rptaylor** [comment]
We found that that authorized_keys file also has the problem. There appears to be some openstack process trying to download http://169.254.169.254/latest/meta-data/public-keys//0/openssh-key  , but we didn't specify any key to be injected into the VM using Cloud Scheduler. So there's no key there. And cloud-init just appends to the file. Maybe it's okay to leave it like this...
