### ISSUE TITLE
condor config in 50cernvm, 40 cernvm files

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#29]
The yaml currently deletes /etc/condor/config.d/50cernvm .
The content of this may have changed - we should take a look.
Also what about 40cernvm?

They seem to contain some condor config that is needed on certain clouds (Mouse, Chameleon) ?

**Comment by rptaylor** [comment]
@berghaus do you recall what was in 50cernvm and why we had to delete it?

**Comment by mhpx** [comment]
There's a difference between what was in 50cernvm that's being deleted and the 40cernvm that we were replacing it with.

**Comment by rd37** [comment]
I thought we did it to resolve some chameleon issues ... that is just a
guess!
