### ISSUE TITLE
dual configuration of Shoal client?

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#3]
The cloud-init scripts have both this:

shoal:
shoal_server_url: http://shoal.heprc.uvic.ca/nearest
cron_shoal: '0,30 * * * * /usr/bin/shoal-client'

and this:

    - content: |
    #
    # A sample configuration file for shoal client.
    #
    [general]
    cvmfs_config = /etc/cvmfs/default.local
    shoal_server_url = http://shoal.heprc.uvic.ca/nearest
    default_squid_proxy = http://kraken01.westgrid.ca:3128;http://cernvm-webfs.atlas-canada.ca:3128
    owner: root:root
    path: /etc/shoal/shoal_client.conf
    permissions: '0644'

Not sure which one is being used, but the other should be removed.
@berghaus ?

**Comment by berghaus** [comment]
When setting this up I found that the shoal.conf did not reflect the content in the shoal yaml blob. I added the write file statement to fix this but kept the (non-functional) shoal yaml blob for reference. Maybe this is fixed now? Check what happens when you remove the write file statement.

**Comment by rptaylor** [comment]
The yaml blob appears to work:
    # cat /etc/crontab_shoal 
    0,30 * * * * /usr/bin/shoal-client

However,
A) There should be a newline at the end of the file
    Mon Feb 23 19:40:23 2015: "/etc/crontab_shoal":1: premature EOF
    Mon Feb 23 19:40:23 2015: errors in crontab file, can't install.
B) `/etc/crontab_shoal` is not a suitable location for the file. It should be in /etc/cron.d/


I'm not sure what's happening with `shoal_client.conf` I think it may be getting configured by both methods, but still isn't correct.

**Comment by rptaylor** [comment]
What specifies the location of the file (`/etc/crontab_shoal`) produced by the "cron_shoal" property?

**Comment by rptaylor** [comment]
Related: https://github.com/cinquo/cloud-init-cern/issues/15

**Comment by rptaylor** [comment]
These fixes should be applied in cern-cloudinit-latest-2-2.8.noarch in CernVM 3.4.
Then the yaml should be tested and used instead of the write_files statement.
