### ISSUE TITLE
condor chkconfig

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#4]
runcmd includes:

 - [ chkconfig, condor, on ]

This maybe isn't needed since the VMs don't reboot. For some reason it's getting changed to 'chkconfig' 'condor' 'True'  in the scripts/runcmd file in the instance.  That is an invalid command.

The VMs don't have condor turned on in chkconfig anyway:

    # chkconfig --list condor
    condor         	0:off	1:off	2:off	3:off	4:off	5:off	6:off

**Comment by berghaus** [comment]
This was added to help with manual intervention on the worker nodes, but you are right it is not necessary since usually the VMs do no reboot during their lifecycle.

**Comment by rd37** [comment]
quick reboot would decrease developement times when creating new cloud-init
files and testing them I think

**Comment by rptaylor** [comment]
Even if the VMs do reboot, it would still be best to do (rather, redo) all the contextualization first, and start condor last. I think that's what we always want, so it's another reason to remove the chkconfig statement I think.
