### ISSUE TITLE
network tuning

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#5]
We used to have some stuff in /etc/sysctl.conf

```
# Network tuning: http://fasterdata.es.net/fasterdata/host-tuning/linux/
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216 
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.core.netdev_max_backlog = 30000
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
```

Then do `sysctl -p`

And in /etc/rc.local

```
# increase txqueuelen for 10G NICS
/sbin/ifconfig eth0 txqueuelen 10000</verbatim>
```

Should we re-introduce this network tuning?

**Comment by rd37** [comment]
I can do some testing with the settings

**Comment by berghaus** [comment]
The network tuning was in the cloud init user data until a few months ago when the commands setting these parameters started crashing cloud-init (Ron I think you recall having to remove those commands). Is it sensible to rewrite the sysctl.conf with cloud init? Not sure if this could mess up some local configs on some of the clouds.

How about adding the commands to set the sysctl parameters to the rc.local as well?

**Comment by rptaylor** [comment]
True, we shouldn't rewrite sysctl.conf.
Newer linux versions have /etc/sysctl.d/ which would work well.

Maybe the best would be to just do it in runcmd for now.

**Comment by berghaus** [comment]
Hi Ryan,

What is what I mean with my previous comment: we use to do this using runcmd. Then something in cloud-init changed and those statements no longer worked.

So my suggestion is: write a file to /etc/sysctl.d/

If that is a problem add the relevant command to the /etc/rc.local

Cheers,
-Frank
