### ISSUE TITLE
add grid.cern.ch to list of CVMFS repos

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#6]
We may not need it, but CernVM uses it for this symlink:
` /etc/grid-security/certificates -> /cvmfs/grid.cern.ch/etc/grid-security/certificates`

**Comment by berghaus** [comment]
We need those CA certs to authenticate via GSI, so it is probably better to explicitly add the repo.

**Comment by berghaus** [comment]
I'll let you guys decide whether to take my changes/close this issue ;-)

**Comment by rptaylor** [comment]
Agreed (although the jobs use CA certs from a different location (via ALRB)).
