### ISSUE TITLE
condor jobwrapper runs after profile.d scripts

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloudinit-userdata#9]
We're using the condor jobwrapper to set HOME:
            export HOME=`eval echo ~$USER`
 However this used to be done in /etc/profile.d/grid-setup.sh . It appears that moving this line to the jobwrapper is the cause of https://its.cern.ch/jira/browse/ATLASCI-15 , because ALRB is set up in grid-setup.sh before HOME is set by the job wrapper.

@berghaus do you know why this was changed? Was it done to fix another issue?
Just trying to figure out if anything else might break if I change it back.

**Comment by berghaus** [comment]
We were setting HOME in both the profile.d script and the jobwrapper. At the time we considered the jobwrapper to be the appropriate place, but there was not bug/problem attached the the decision. So it should be find to move this to the grid-setup.sh

**Comment by rptaylor** [comment]
Okay, thanks for the info!
